@startuml

!include <C4/C4_Container>
!theme C4_superhero from <C4/themes>

Container_Boundary(data_platform, "Data Platform") {
    !include ../../src/data_platform/kafka.puml
    !include ../../src/data_platform/clickhouse.puml
    !include ../../src/data_platform/postgresql.puml
    !include ../../src/data_platform/dbt.puml
    !include ../../src/data_platform/s3.puml

    Component(ingestion_service, "Ingestion Service", "Python", "Ingests data from external sources")
    Component(processing_service, "Processing Service", "Apache Spark", "Processes and transforms data")
}

Rel(ingestion_service, kafka_cluster, "Publishes messages to")
Rel(kafka_cluster, processing_service, "Streams data to")
Rel(processing_service, postgresql_db, "Stores transformed data in")
Rel(processing_service, clickhouse_db, "Stores analytics data in")
Rel(processing_service, s3_bucket, "Stores processed data in S3")
Rel(dbt_tool, postgresql_db, "Transforms data in")
Rel(dbt_tool, clickhouse_db, "Transforms data in")

@enduml
