@startuml 

!include <C4/C4_Component>

Component(postgresql_db, "PostgreSQL Database", "PostgreSQL", "Relational database for transactional data")
postgresql_db -> postgresql_db : "IP Address: 10.10.1.102\nDNS: postgresql.prod.local\nVersion: 13"

@enduml
