@startuml
!include ../components/data_sources.puml
!include ../components/storage.puml
!include ../components/processing.puml

CRM -right-> ETL
ERP -right-> ETL
Marketing -left-> ETL
CustomerData -left-> ETL

ETL -down-> DataLake
ETL -down-> DataWarehouse

@enduml
